language: csharp
solution: ./src/BinarySearchTree.sln
mono: none
dotnet: 2.1.403

install:
  - dotnet restore ./src/

script:
  - dotnet build ./src/
  - dotnet test ./src/BinarySearchTree.Test/BinarySearchTree.Test.csproj
